# MySQL
spring:
  datasource:
    url:
      "jdbc:mysql://localhost:3306/courseman"
    username:
      "root"
    driver-class-name:
      "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform:
      "org.hibernate.dialect.MySQL5InnoDBDialect"
    # hibernate:
    #   ddl-auto: 
    #     create
    properties:
      hibernate:
        format_sql:
          true
    show-sql: 
      true  
    
